### ISSUE TITLE
Gitlab SaaS registry sync not working

### ISSUE THREAD

**Issue by daimoniac** [deepfence/ThreatMapper#1965]
**Describe the bug**
gitlab registry can be added and authentication seems to work, yet when trying to sync images nothing happens in the UI, while deepfence-worker throws an exception.

i used the following settings for the registry:
registry name: testreg
gitlab server url: https://gitlab.com
gitlab registry url: registry.gitlab.com/group/subgroup/project (private registry path consisting of group,subgroup and project)
gitlab access token: Personal access token with read_api and read_registry permissions

**To Reproduce**
1. Go to registries/gitlab/add new registry
2. add new registry using the variables posted above
3. Try to sync
4. See error in deepfence-worker

**Expected behavior**
gitlab registry added and images synced

**Components/Services affected**
- [ ] UI/Frontend
- [x] API/Backend
- [ ] Agent
- [ ] Deployment/YAMLs
- [ ] CI/CD Integration
- [ ] Other (specify)

**Additional context**
error log from deepfence-worker:
```
panic occurred: runtime.boundsError{x:0, y:0, signed:true, code:0x0}, stacktrace: 
goroutine 72175 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/deepfence/ThreatMapper/deepfence_worker/utils.Recoverer.func1.1()
	/src/deepfence_worker/utils/asynq.go:32 +0x58
panic({0x36b79a0?, 0xc00259fab8?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab.getImageWithTags({0xc001596318?, 0xc000a8a3d0?}, {0xc0011c2c40, 0x1a}, 0x38?)
	/src/deepfence_worker/vendor/github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab/client.go:132 +0x4cb
github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab.listImages({0xc001596318, 0x12}, {0x15af7d9?, 0xc0010b6dc8?}, {0xc0011c2c40, 0x1a})
	/src/deepfence_worker/vendor/github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab/client.go:60 +0x145
github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab.(*RegistryGitlab).FetchImagesFromRegistry(0xc0010960f0?)
	/src/deepfence_worker/vendor/github.com/deepfence/ThreatMapper/deepfence_server/pkg/registry/gitlab/gitlab.go:69 +0x2e
github.com/deepfence/ThreatMapper/deepfence_server/pkg/registrysync.SyncRegistry({0x409a2a0?, 0xc0008ef9e0}, 0xc0010b7688?, {0x40ac2b8, 0xc0010960f0}, {0x6, {0xc001485af8, 0x6}, {0xc001485b20, 0x6}, ...})
	/src/deepfence_worker/vendor/github.com/deepfence/ThreatMapper/deepfence_server/pkg/registrysync/sync.go:66 +0x47f
github.com/deepfence/ThreatMapper/deepfence_worker/cronjobs.syncRegistry({0x409a2a0, 0xc0008ef9e0}, 0x180?, {0xc000d84820, 0x1, 0xc0012fec60?})
	/src/deepfence_worker/cronjobs/registry.go:93 +0x496
github.com/deepfence/ThreatMapper/deepfence_worker/cronjobs.SyncRegistry({0x409a2a0, 0xc0008ef9e0}, 0xc001444c30)
	/src/deepfence_worker/cronjobs/registry.go:73 +0x8b3
main.(*Worker).AddRetryableHandler.telemetryCallbackWrapper.func1({0x409a2a0, 0xc0008ef9e0}, 0x323b0c0?)
	/src/deepfence_worker/worker.go:52 +0xfb
main.(*Worker).AddRetryableHandler.contextInjectorCallbackWrapper.func2({0x409a348, 0xc0008c7730}, 0xc0012cf9b0?)
	/src/deepfence_worker/worker.go:65 +0x77
github.com/hibiken/asynq.HandlerFunc.ProcessTask(0x12?, {0x409a348?, 0xc0008c7730?}, 0xc001439fa8?)
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/server.go:577 +0x29
github.com/deepfence/ThreatMapper/deepfence_worker/utils.Recoverer.func1({0x409a348?, 0xc0008c7730?}, 0xc001439e80?)
	/src/deepfence_worker/utils/asynq.go:37 +0x83
github.com/hibiken/asynq.HandlerFunc.ProcessTask(0xc0008aa370?, {0x409a348?, 0xc0008c7730?}, 0x50?)
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/server.go:577 +0x29
github.com/hibiken/asynq.(*ServeMux).ProcessTask(0x7f66727ccdb8?, {0x409a348, 0xc0008c7730}, 0xc000780000?)
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/servemux.go:51 +0x42
github.com/hibiken/asynq.(*processor).perform(0xc001439fa8?, {0x409a348?, 0xc0008c7730?}, 0x0?)
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/processor.go:432 +0x75
github.com/hibiken/asynq.(*processor).exec.func1.3()
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/processor.go:230 +0x1ae
created by github.com/hibiken/asynq.(*processor).exec.func1 in goroutine 72174
	/src/deepfence_worker/vendor/github.com/hibiken/asynq/processor.go:219 +0x246\
```

**Comment by shyam-dev** [comment]
Hello @daimoniac  -- Thank you for reporting this issue. The team is working on it and we will post an update here shortly.
