### ISSUE TITLE
[Secrect scan] Show top running containers

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#303]
1. Do a secret scan of any running container, let's say tomcat in this case
2. Even if there are "High" severity secrets on the container, they are not displayed on the top running containers section
![image](https://user-images.githubusercontent.com/34362153/156866270-0de522e5-ebe1-4585-84bc-e22a1786e4a2.png)

**Comment by saurabh2253** [comment]
<img width="1789" alt="Screenshot 2022-03-06 at 10 32 18 AM" src="https://user-images.githubusercontent.com/3922581/156914151-26bb2c59-5639-4658-bfb7-4fc3341e4da9.png">
showing up now

**Comment by jo19in1** [comment]
![image](https://user-images.githubusercontent.com/34362153/157599905-528bff60-81d4-431d-96f8-9fca84aa03fc.png)

**Comment by jo19in1** [comment]
```
Logs from API container logs:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 589, in secret_exposing_nodes
    image_data["node"] = scan_id_bkt["container_name"]["buckets"][0]["key"]
IndexError: list index out of range
ERROR:config.app:Exception on /deepfence/v1.5/secret/top_exposing_nodes [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 589, in secret_exposing_nodes
    image_data["node"] = scan_id_bkt["container_name"]["buckets"][0]["key"]
IndexError: list index out of range
```

**Comment by mukuldeepfence** [comment]
![image](https://user-images.githubusercontent.com/72725782/157841482-a7f6674d-0e36-47e4-add9-b9a8862179c5.png)

**Comment by ibreakthecloud** [comment]
reopen if required
