### ISSUE TITLE
[500 internal server error] on secrect scan results page

### ISSUE THREAD

**Issue by jo19in1** [deepfence/ThreatMapper#342]
1. Deploy management console on a regular vm and connect a regular vm agent to it.
2.  Scan the vm for secrets. Delete one of the scan results
3.  I see that the secret scan api gives 500 error

`/deepfence/v1.5/enumerate_filters?resource_type=secret-scan&
`
![image](https://user-images.githubusercontent.com/34362153/158310292-6529c959-0d50-467c-a75b-de434dbf46ad.png)

4. Here are the API container logs

```
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [2073146346/1.9gb], which is larger than the limit of [1973865676/1.8gb], real usage: [2073145632/1.9gb], new bytes reserved: [714/714b], usages [request=0/0b, fielddata=3749/3.6kb, in_flight_requests=714/714b, accounting=79776/77.9kb]')
ERROR:config.app:Exception on /deepfence/v1.5/enumerate_filters [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 127, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/resource_api.py", line 972, in enumerate_node_filters
    secret_scan_aggs = ESConn.aggregation_helper(
  File "/app/code/utils/esconn.py", line 1298, in aggregation_helper
    return EL_CLIENT.search(index=index_name, body=aggs_query)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/utils.py", line 152, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/client/__init__.py", line 1658, in search
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 392, in perform_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/http_urllib3.py", line 269, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py", line 315, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch.exceptions.TransportError: TransportError(429, 'circuit_breaking_exception', '[parent] Data too large, data for [<http_request>] would be [2073146346/1.9gb], which is larger than the limit of [1973865676/1.8gb], real usage: [2073145632/1.9gb], new bytes reserved: [714/714b], usages [request=0/0b, fielddata=3749/3.6kb, in_flight_requests=714/714b, accounting=79776/77.9kb]')
```

**Comment by jatin-baweja** [comment]
This has been fixed in https://github.com/deepfence/ThreatMapper/pull/347

**Comment by jo19in1** [comment]
Looking good .I do not see this error anymore
