### ISSUE TITLE
deepfence-api and deepfence-ui problem

### ISSUE THREAD

**Issue by sannour** [deepfence/ThreatMapper#39]
Problem:
cannot switch tabs inside deepfence-ui, ui stuck at loading topology page with "verifying topologies message"

Expected:
to be able to browse the ui normally

 
[deepfence-api_logs.txt.gz](https://github.com/deepfence/ThreatMapper/files/5339043/deepfence-api_logs.txt.gz)
![2020-10-07_10-56](https://user-images.githubusercontent.com/13887950/95303423-d3b0fc80-088b-11eb-9bed-8678684da919.png)

truncated deepfence-api container logs  below

```
[2020-10-07 07:27:41 +0000] [97] [ERROR] Exception on /deepfence/v1.5/node_status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_restful/__init__.py", line 272, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "api/common_api.py", line 1424, in api.common_api.get_node_status
  File "api/common_api.py", line 1433, in api.common_api.determine_node_status
  File "api/common_api.py", line 1552, in api.common_api.get_topology_cve_status
  File "utils/esconn.py", line 2823, in utils.esconn.ESConn.group_by
  File "utils/esconn.py", line 503, in utils.esconn.ESConn.search
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1623, in search
    body=body,
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/transport.py", line 362, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 282, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'field name is null or empty')
ERROR:config.df_app:Exception on /deepfence/v1.5/node_status [GET]
Traceback (most recent call last):
```

**Comment by sannour** [comment]
Found out that i must use a valid email address to register the user, had to destroy the containers and create again.
now it's working fine
