### ISSUE TITLE
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying.

### ISSUE THREAD

**Issue by ShahidAkhterSec** [deepfence/ThreatMapper#607]
Hey there , i am getting this error from docker composition locally.
It gives this error:
eepfence-console-agent           | fs.file-max = 1048576
deepfence-console-agent           | fs.nr_open = 1048576
deepfence-console-agent           | net.core.somaxconn = 10240
deepfence-console-agent           | net.ipv4.tcp_mem = 1048576 1048576 1048576
deepfence-console-agent           | net.ipv4.tcp_max_syn_backlog = 1024
deepfence-console-agent           | net.ipv4.ip_local_port_range = 1024 65534
deepfence-console-agent           | Start agent authentication...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...
deepfence-console-agent           | Could not connect to Deepfence Management Console. Retrying...

**Comment by ramanan-ravi** [comment]
Hi @ShahidAkhterSec , can you check if `deepfence-api` and `deepfence-router` containers are running?
```
docker logs deepfence-api
docker logs deepfence-router
```

**Comment by ShahidAkhterSec** [comment]
docker logs deepfence-api
docker logs deepfence-router
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to deepfence-es port 9200: Connection refused
Elastic search is unavailable - sleeping
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   542  100   542    0     0   1048      0 --:--:-- --:--:-- --:--:--  1046
{
  "name" : "deepfence-es",
  "cluster_name" : "df-es-cluster",
  "cluster_uuid" : "VnW8zMHwQ3ip3mhaVAYSJA",
  "version" : {
    "number" : "7.17.5",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "8d61b4f7ddf931f219e3745f295ed2bbc50c8e84",
    "build_date" : "2022-06-23T21:57:28.736740635Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
Adding elasticsearch custom configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   376  100    21  100   355     21    360  0:00:01 --:--:--  0:00:01   381
{"acknowledged":true}
Adding deepfence indices
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   982  100    62  100   920     76   1141 --:--:-- --:--:-- --:--:--  1216
{"acknowledged":true,"shards_acknowledged":true,"index":"cve"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   710  100    67  100   643    272   2613 --:--:-- --:--:-- --:--:--  2886
{"acknowledged":true,"shards_acknowledged":true,"index":"cve-scan"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   776  100    72  100   704    444   4345 --:--:-- --:--:-- --:--:--  4790
{"acknowledged":true,"shards_acknowledged":true,"index":"sbom-cve-scan"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   243  100    54  14294   3176 --:--:-- --:--:-- --:--:-- 17470
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1944  100    72  100  1872    325   8470 --:--:-- --:--:-- --:--:--  8796
{"acknowledged":true,"shards_acknowledged":true,"index":"sbom-artifact"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   422  100    65  100   357    371   2040 --:--:-- --:--:-- --:--:--  2397
{"acknowledged":true,"shards_acknowledged":true,"index":"report"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1201  100    70  100  1131    264   4267 --:--:-- --:--:-- --:--:--  4532
{"acknowledged":true,"shards_acknowledged":true,"index":"secret-scan"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1206  100    75  100  1131    246   3720 --:--:-- --:--:-- --:--:--  3967
{"acknowledged":true,"shards_acknowledged":true,"index":"secret-scan-logs"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   971  100    69  100   902    213   2792 --:--:-- --:--:-- --:--:--  3006
{"acknowledged":true,"shards_acknowledged":true,"index":"compliance"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   982  100    80  100   902    484   5466 --:--:-- --:--:-- --:--:--  5915
{"acknowledged":true,"shards_acknowledged":true,"index":"cloud-compliance-scan"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   718  100    79  100   639    379   3072 --:--:-- --:--:-- --:--:--  3468
{"acknowledged":true,"shards_acknowledged":true,"index":"compliance-scan-logs"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   724  100    85  100   639    480   3610 --:--:-- --:--:-- --:--:--  4090
{"acknowledged":true,"shards_acknowledged":true,"index":"cloud-compliance-scan-logs"}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1178  100    75  100  1103    382   5627 --:--:-- --:--:-- --:--:--  6010
{"acknowledged":true,"shards_acknowledged":true,"index":"cloudtrail-alert"}
Adding cve map pipeline
200

Adding cve scan map pipeline
200

Adding compliance_pipeline
200

Adding compliance_scan_logs_pipeline
200

Adding default_upsert indexed script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100    21  100   395    272   5129 --:--:-- --:--:-- --:--:--  5402
{"acknowledged":true}
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchDeprecationWarning)

custom configuration added successfully
deepfence-postgres:5432 - accepting connections
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 33186242cc85, empty message
INFO  [alembic.runtime.migration] Running upgrade 33186242cc85 -> 78e539ba017b, empty message
INFO  [alembic.runtime.migration] Running upgrade 78e539ba017b -> 7157dfe14c8b, empty message
INFO  [alembic.runtime.migration] Running upgrade 7157dfe14c8b -> 9e7bf92d39d6, empty message
INFO  [alembic.runtime.migration] Running upgrade 9e7bf92d39d6 -> 872400bf5320, empty message
INFO  [alembic.runtime.migration] Running upgrade 872400bf5320 -> a0e09efd0afc, empty message
Creating user roles
Created df_cluster_id 2485377957901
Finished creating user roles
[2022-10-05 11:28:22 +0000] [152] [INFO] Starting gunicorn 20.1.0
[2022-10-05 11:28:22 +0000] [152] [INFO] Listening at: http://0.0.0.0:9998 (152)
[2022-10-05 11:28:22 +0000] [152] [INFO] Using worker: gevent
[2022-10-05 11:28:22 +0000] [153] [INFO] Booting worker with pid: 153
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchDeprecationWarning)
[2022-10-05 12:49:11 +0000] [153] [ERROR] Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
ERROR:config.app:Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
[2022-10-05 12:49:14 +0000] [153] [ERROR] Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
ERROR:config.app:Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
[2022-10-05 12:49:15 +0000] [153] [ERROR] Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
ERROR:config.app:Exception on /deepfence/v1.5/secret/scan_registry [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.9/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/site-packages/flask_jwt_extended/view_decorators.py", line 154, in decorator
    return current_app.ensure_sync(fn)(*args, **kwargs)
  File "/app/code/api/secret_scan_api.py", line 404, in secret_scan_results
    image_df['timestamp'] = pd.to_datetime(image_df.pushed_at)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'pushed_at'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{
  "name" : "deepfence-es",
  "cluster_name" : "df-es-cluster",
  "cluster_uuid" : "VnW8zMHwQ3ip3mhaVAYSJA",
  "version" : {
    "number" : "7.17.5",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "8d61b4f7ddf931f219e3745f295ed2bbc50c8e84",
    "build_date" : "2022-06-23T21:57:28.736740635Z",
    "build_snapshot" : false,
    "lucene_version" : "8.11.1",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
100   542  100   542    0     0  25809      0 --:--:-- --:--:-- --:--:-- 25809
Adding elasticsearch custom configuration
Adding deepfence indices
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1273  100   353  100   920  44125   112k --:--:-- --:--:-- --:--:--  155k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cve/kpQ1rSaNRiqfk-jDyjviIA] already exists","index_uuid":"kpQ1rSaNRiqfk-jDyjviIA","index":"cve"}],"type":"resource_already_exists_exception","reason":"index [cve/kpQ1rSaNRiqfk-jDyjviIA] already exists","index_uuid":"kpQ1rSaNRiqfk-jDyjviIA","index":"cve"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1016  100   373  100   643  93250   156k --:--:-- --:--:-- --:--:--  248k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cve-scan/oT16fA4nSiKW4W0hB_OKcQ] already exists","index_uuid":"oT16fA4nSiKW4W0hB_OKcQ","index":"cve-scan"}],"type":"resource_already_exists_exception","reason":"index [cve-scan/oT16fA4nSiKW4W0hB_OKcQ] already exists","index_uuid":"oT16fA4nSiKW4W0hB_OKcQ","index":"cve-scan"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1097  100   393  100   704  98250   171k --:--:-- --:--:-- --:--:--  267k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [sbom-cve-scan/XlwLK0ZrT1ezqeepCw1sdQ] already exists","index_uuid":"XlwLK0ZrT1ezqeepCw1sdQ","index":"sbom-cve-scan"}],"type":"resource_already_exists_exception","reason":"index [sbom-cve-scan/XlwLK0ZrT1ezqeepCw1sdQ] already exists","index_uuid":"XlwLK0ZrT1ezqeepCw1sdQ","index":"sbom-cve-scan"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   297  100   243  100    54  48600  10800 --:--:-- --:--:-- --:--:-- 74250
{"error":{"root_cause":[{"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"}],"type":"action_request_validation_exception","reason":"Validation Failed: 1: no settings to update;"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2265  100   393  100  1872  78600   365k --:--:-- --:--:-- --:--:--  442k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [sbom-artifact/5E2uS4CMRRaejjBtQ2X5Sg] already exists","index_uuid":"5E2uS4CMRRaejjBtQ2X5Sg","index":"sbom-artifact"}],"type":"resource_already_exists_exception","reason":"index [sbom-artifact/5E2uS4CMRRaejjBtQ2X5Sg] already exists","index_uuid":"5E2uS4CMRRaejjBtQ2X5Sg","index":"sbom-artifact"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   722  100   365  100   357  52142  51000 --:--:-- --:--:-- --:--:--  117k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [report/ZnBnrgmWQnqi_334i6Plow] already exists","index_uuid":"ZnBnrgmWQnqi_334i6Plow","index":"report"}],"type":"resource_already_exists_exception","reason":"index [report/ZnBnrgmWQnqi_334i6Plow] already exists","index_uuid":"ZnBnrgmWQnqi_334i6Plow","index":"report"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1516  100   385  100  1131  77000   220k --:--:-- --:--:-- --:--:--  296k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [secret-scan/n_PvynInRqCvvgiaTMfblQ] already exists","index_uuid":"n_PvynInRqCvvgiaTMfblQ","index":"secret-scan"}],"type":"resource_already_exists_exception","reason":"index [secret-scan/n_PvynInRqCvvgiaTMfblQ] already exists","index_uuid":"n_PvynInRqCvvgiaTMfblQ","index":"secret-scan"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1536  100   405  100  1131  81000   220k --:--:-- --:--:-- --:--:--  300k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [secret-scan-logs/RZ_u6G_QRgSNSfPwtrRBIg] already exists","index_uuid":"RZ_u6G_QRgSNSfPwtrRBIg","index":"secret-scan-logs"}],"type":"resource_already_exists_exception","reason":"index [secret-scan-logs/RZ_u6G_QRgSNSfPwtrRBIg] already exists","index_uuid":"RZ_u6G_QRgSNSfPwtrRBIg","index":"secret-scan-logs"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [compliance/nvGCzaH-Si6VSF1HiBQVJg] already exists","index_uuid":"nvGCzaH-Si6VSF1HiBQVJg","index":"compliance"}],"type":"resource_already_exists_exception","reason":"index [compliance/nvGCzaH-Si6VSF1HiBQVJg] already exists","index_uuid":"nvGCzaH-Si6VSF1HiBQVJg","index":"compliance"},"status":400}
100  1283  100   381  100   902  76200   176k --:--:-- --:--:-- --:--:--  250k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1327  100   425  100   902  85000   176k --:--:-- --:--:-- --:--:--  259k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cloud-compliance-scan/NeOasuyzRxe-ZaBzg4smmA] already exists","index_uuid":"NeOasuyzRxe-ZaBzg4smmA","index":"cloud-compliance-scan"}],"type":"resource_already_exists_exception","reason":"index [cloud-compliance-scan/NeOasuyzRxe-ZaBzg4smmA] already exists","index_uuid":"NeOasuyzRxe-ZaBzg4smmA","index":"cloud-compliance-scan"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1060  100   421  100   639  84200   124k --:--:-- --:--:-- --:--:--  207k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [compliance-scan-logs/XWBcdZA_R32R7Tq3Pl6J7g] already exists","index_uuid":"XWBcdZA_R32R7Tq3Pl6J7g","index":"compliance-scan-logs"}],"type":"resource_already_exists_exception","reason":"index [compliance-scan-logs/XWBcdZA_R32R7Tq3Pl6J7g] already exists","index_uuid":"XWBcdZA_R32R7Tq3Pl6J7g","index":"compliance-scan-logs"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1084  100   445  100   639  89000   124k --:--:-- --:--:-- --:--:--  211k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cloud-compliance-scan-logs/9CfhXSkJSW2YvtBWBYWX5A] already exists","index_uuid":"9CfhXSkJSW2YvtBWBYWX5A","index":"cloud-compliance-scan-logs"}],"type":"resource_already_exists_exception","reason":"index [cloud-compliance-scan-logs/9CfhXSkJSW2YvtBWBYWX5A] already exists","index_uuid":"9CfhXSkJSW2YvtBWBYWX5A","index":"cloud-compliance-scan-logs"},"status":400}
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1508  100   405  100  1103  81000   215k --:--:-- --:--:-- --:--:--  294k
{"error":{"root_cause":[{"type":"resource_already_exists_exception","reason":"index [cloudtrail-alert/BHgv6BpxTkSehvEj5dZdiA] already exists","index_uuid":"BHgv6BpxTkSehvEj5dZdiA","index":"cloudtrail-alert"}],"type":"resource_already_exists_exception","reason":"index [cloudtrail-alert/BHgv6BpxTkSehvEj5dZdiA] already exists","index_uuid":"BHgv6BpxTkSehvEj5dZdiA","index":"cloudtrail-alert"},"status":400}
Adding cve map pipeline
200

Adding cve scan map pipeline
200

Adding compliance_pipeline
200

Adding compliance_scan_logs_pipeline
200

Adding default_upsert indexed script
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   416  100    21  100   395    567  10675 --:--:-- --:--:-- --:--:-- 10947
{"acknowledged":true}
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchDeprecationWarning)

custom configuration added successfully
deepfence-postgres:5432 - accepting connections
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Creating user roles
Finished creating user roles
Unlinking stale socket /var/run/supervisor.sock
[2022-10-05 13:03:11 +0000] [120] [INFO] Starting gunicorn 20.1.0
[2022-10-05 13:03:11 +0000] [120] [INFO] Listening at: http://0.0.0.0:9998 (120)
[2022-10-05 13:03:11 +0000] [120] [INFO] Using worker: gevent
[2022-10-05 13:03:11 +0000] [121] [INFO] Booting worker with pid: 121
/usr/local/lib/python3.9/site-packages/elasticsearch/connection/base.py:193: ElasticsearchDeprecationWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchDeprecationWarning)
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Starting router
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Waiting for containers to start up
Starting router

**Comment by ShahidAkhterSec** [comment]
That's what i have got after running those commands.

**Comment by ShahidAkhterSec** [comment]
Is there any progress?
